### ISSUE TITLE
RangeReduce Error ?

### ISSUE THREAD

**Issue by tilient** [ExaScience/pargo#1] opened 2017-09-03 10:11 UTC
I think there is an error in the **RangeReduce** (and friends) code.
At line 752 in "_parallel.go_" it mentions `if mid >= half {`.
I guess that needs to be `if mid >= high {`.
With that change, it does work correct for me. The original code always gives me just 1 slice.

**Comment by pcostanza** [comment] 2017-09-03 10:46
You are right, this was probably caused by an auto-completion typo which then carried over to several places of the code through copy-and-paste. This should be fixed now. Thanks for reporting this.

**Closed by pcostanza** 2017-09-03 10:46 UTC
